### ISSUE TITLE
Does this only work with MP4 AVC or do others work

### ISSUE THREAD

**Issue by Gamer4Life2020** [prs-eth/RollingDepth#13]
I finally got it running but only on the samples, none of my video's work. So far looks to be somewhat faster than DepthCrafter and equal or better results on fast haven't tried other settings yet. If needed I could covert videos to AVC mp4 first if there is no way or plans to include others at this time.

Format                      : MPEG-4
Format profile              : QuickTime
Codec ID                    : qt   0000.02 (qt  )
File size                   : 495 MiB
Duration                    : 2 min 3 s
Overall bit rate            : 33.5 Mb/s
Frame rate                  : 24.000 FPS
Encoded date                : 2024-12-03 01:24:14 UTC
Tagged date                 : 2024-12-03 01:24:14 UTC
Writing application         : Blackmagic Design DaVinci Resolve Studio

Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main@L5.2@High
Codec ID                    : hvc1
Codec ID/Info               : High Efficiency Video Coding
Duration                    : 2 min 3 s
Bit rate                    : 31.2 Mb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 24.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0

https://drive.google.com/file/d/1BC-Eqx5veU7HDkC0NAt6keWC-pdAS8wZ/view?usp=sharing

**Comment by markkua** [comment]
What do you mean by none of your videos work? Do they fail to be loaded or the predictions don't look reasonable? If it's related to video loading, I would suggest to check / update your ffmpeg. 

> We use [pyav](https://github.com/PyAV-Org/PyAV) for video I/O, which relies on [ffmpeg](https://www.ffmpeg.org/) (tested with version 5.1.6-0+deb12u1)

**Comment by Gamer4Life2020** [comment]
Ok, I'll update ffmpg and see. Sorry to keep bothering you I'm just looking for the best depthmaps for video editing as most anything is better than Resolves built-in one.

(rollingdepth) acdl@DESKTOP-P5CDBPJ:/mnt/c/Users/ACDL/RollingDepth$ python run_video.py -i ./data/samples -o ./output/samples_fast -p fast --save-npy false --save-sbs false --verbose
!!!!!!!!!!!!!! [RollingDepth] Using modified Diffusers for cross-frame self-attention !!!!!!!!!!!!!!
INFO:root:Using preset: fast
INFO:root:arguments: {'res': 768, 'snippet_lengths': [3], 'cap_dilation': True, 'dtype': 'fp16', 'refine_snippet_len': 3, 'refine_start_dilation': 6, 'dilations': [1, 25], 'refine_step': 0, 'input_video': './data/samples', 'output_dir': './output/samples_fast', 'preset': 'fast', 'start_frame': 0, 'frame_count': 0, 'checkpoint': 'prs-eth/rollingdepth-v1-0', 'max_vae_bs': 4, 'output_fps': 0, 'restore_res': False, 'save_sbs': False, 'save_npy': False, 'save_snippets': False, 'color_maps': ['Spectral_r', 'Greys_r'], 'resample_method': 'BILINEAR', 'unload_snippet': False, 'verbose': True, 'seed': None}
INFO:root:device = cuda
INFO:root:Found 3 videos.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.75it/s]
INFO:root:xformers enabled
Processing videos:   0%|                  INFO:root:2973 frames loaded from video data/samples/Life w father 3D test.mov
Killed
(rollingdepth) acdl@DESKTOP-P5CDBPJ:/mnt/c/Users/ACDL/RollingDepth$

**Comment by markkua** [comment]
Judging by `Killed`, I suspect it's caused by "out of CPU memory (RAM)" when loading the video. The video you share is pretty long and takes ~60G RAM on my PC at the resolution of 768. If you have limited RAM, I suggest to process shorter clips, e.g. by setting `--frames 1000 `, or/and use a smaller processing resolution, e.g. `--res 512`.

**Comment by Gamer4Life2020** [comment]
Ok, that is what I was wondering if there was a way to run batches or something I'll try that. Yes, I only have 64GB

**Comment by Gamer4Life2020** [comment]
Ok, that works fine. Thanks, now I need to figure out a bat file or see if ChatGPT can make one to help automate it.
Going from 1000 and starting at 1001 seems fine and nothing seems missing.

python run_video.py -i ./data/samples/LWFMOV -o ./output/samples_fast -p fast --save-npy false --save-sbs false --frames 1000 --verbose

python run_video.py -i ./data/samples/LWFMOV -o ./output/samples_fast -p fast --save-npy false --save-sbs false --frames 1000 --from 1001 --verbose
