### ISSUE TITLE
FPS is off showing 24 fps not 23.976

### ISSUE THREAD

**Issue by Gamer4Life2020** [prs-eth/RollingDepth#14]
![RD-Output](https://github.com/user-attachments/assets/6a7b656d-dfbb-4dbc-a0c4-5aa3ae23ecf2)
I have looked into what I could and tried --fps 23.976 but failed. Also, tried editing the run.py fps from 'int' to 'float' in the two places I could find for output. It didn't break anything but still shows 24 fps. Other than that, all has been well, I'm just splitting the videos and doing in 1 min batches.

**Comment by Gamer4Life2020** [comment]
Changed to output as png instead of video and I can make whatever fps is needed.

**Comment by markkua** [comment]
You can use ffmpeg to change the fps, or read the depth from the npy file.
