### ISSUE TITLE
Output video resulting with noise

### ISSUE THREAD

**Issue by max-sho** [prs-eth/RollingDepth#6]
Error with output video after running inference
<img width="1789" alt="Screenshot 2024-12-02 at 20 19 41" src="https://github.com/user-attachments/assets/183bb4d1-c94c-4872-b896-6cd2705b56c7">

**Comment by max-sho** [comment]
<img width="1769" alt="Screenshot 2024-12-02 at 22 55 40" src="https://github.com/user-attachments/assets/c4faa41f-2fdc-48ea-bfa0-4ba301cae6e1">
Also

**Comment by markkua** [comment]
Hi, could you share the input video and the command?

**Comment by max-sho** [comment]
https://drive.google.com/file/d/1h0yFPph2HwV6XdNHCHvKwD60eQzcUvOa/view?usp=share_link 

!python run_video.py -i /content/gdrive/MyDrive/DepthVideo001/Mamour.mp4 -o /content/gdrive/MyDrive/DepthVideo001 --res 0 --fps 0 -p full  --max-vae-bs 1 --unload-snippet true --verbose --save-npy false

**Comment by markkua** [comment]
Hi, I ran with the default setting and got a reasonable result: 
```bash
python run_video.py -i data/sample_temp/Mamour.mp4 -o output/samples_fast -p fast --verbose        
```

![image](https://github.com/user-attachments/assets/7cd30c09-f56d-4b63-bc28-1ee57fc61e09)
