### ISSUE TITLE
Run error：num_view

### ISSUE THREAD

**Issue by juntaosun** [prs-eth/RollingDepth#8]
Processing videos:   0%|                                                                                                                                           | 0/1 [00:13<?, ?it/s] 
Traceback (most recent call last):
rollingdepth_pipeline.py", line 645, in single_step
    assert 2 == num_view, f"only implemented for 2-view, got {rgb_latent.shape}"
AssertionError: only implemented for 2-view, got torch.Size([1, 3, 4, 36, 64])

rollingdepth\rollingdepth_pipeline.py", line 652, in single_step
TypeError: UNet2DConditionModel.forward() got an unexpected keyword argument 'num_view'

```
python run_video.py -i data/samples/2_horse.mp4 -o output/samples_fast -p fast --save-npy false --verbose --max-vae-bs 1  --unload-snippet true  --res 512 
```

**Comment by markkua** [comment]
Please install the our modified diffusers `bash script/install_diffusers_dev.sh`
