### ISSUE TITLE
How exactly was Diffusers modified?

### ISSUE THREAD

**Issue by jypjypjypjyp** [prs-eth/RollingDepth#9]
Hello,  great work, but I have a confusion:
Why not use the way of referencing the original Diffusers library to customize a new pipeline locally, but put the entire Diffusers into the repository instead? This is not very user-friendly for readers.

**Comment by markkua** [comment]
Hi, please search for “Modified in RollingDepth” to see the modifications.

**Comment by jypjypjypjyp** [comment]
> Hi, please search for “Modified in RollingDepth” to see the modifications.

Thank you very much.
